// Date: 16/07/2012 12:22:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Bellumacraft.design;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelChaise extends ModelBase
{
  //fields
    ModelRenderer pied2;
    ModelRenderer pied3;
    ModelRenderer pied4;
    ModelRenderer pied1;
    ModelRenderer siege;
    ModelRenderer barre;
    ModelRenderer barre1;
    ModelRenderer barre2;
  
  public ModelChaise()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      pied2 = new ModelRenderer(this, 56, 0);
      pied2.addBox(0F, 0F, 0F, 2, 22, 2);
      pied2.setRotationPoint(-6F, 2F, 4F);
      pied2.setTextureSize(64, 32);
      pied2.mirror = true;
      setRotation(pied2, 0F, 0F, 0F);
      pied3 = new ModelRenderer(this, 56, 0);
      pied3.addBox(0F, 0F, 0F, 2, 22, 2);
      pied3.setRotationPoint(4F, 2F, 4F);
      pied3.setTextureSize(64, 32);
      pied3.mirror = true;
      setRotation(pied3, 0F, 0F, 0F);
      pied4 = new ModelRenderer(this, 0, 0);
      pied4.addBox(0F, 0F, 0F, 2, 10, 2);
      pied4.setRotationPoint(4F, 14F, -6F);
      pied4.setTextureSize(64, 32);
      pied4.mirror = true;
      setRotation(pied4, 0F, 0F, 0F);
      pied1 = new ModelRenderer(this, 0, 0);
      pied1.addBox(0F, 0F, 0F, 2, 10, 2);
      pied1.setRotationPoint(-6F, 14F, -6F);
      pied1.setTextureSize(64, 32);
      pied1.mirror = true;
      setRotation(pied1, 0F, 0F, 0F);
      siege = new ModelRenderer(this, 8, 0);
      siege.addBox(0F, 0F, 0F, 12, 2, 12);
      siege.setRotationPoint(-6F, 12F, -6F);
      siege.setTextureSize(64, 32);
      siege.mirror = true;
      setRotation(siege, 0F, 0F, 0F);
      barre = new ModelRenderer(this, 8, 14);
      barre.addBox(0F, 0F, 0F, 12, 2, 2);
      barre.setRotationPoint(-6F, 0F, 4F);
      barre.setTextureSize(64, 32);
      barre.mirror = true;
      setRotation(barre, 0F, 0F, 0F);
      barre1 = new ModelRenderer(this, 0, 12);
      barre1.addBox(0F, 0F, 0F, 1, 10, 1);
      barre1.setRotationPoint(-2F, 2F, 5F);
      barre1.setTextureSize(64, 32);
      barre1.mirror = true;
      setRotation(barre1, 0F, 0F, 0F);
      barre2 = new ModelRenderer(this, 0, 12);
      barre2.addBox(0F, 0F, 0F, 1, 10, 1);
      barre2.setRotationPoint(1F, 2F, 5F);
      barre2.setTextureSize(64, 32);
      barre2.mirror = true;
      setRotation(barre2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    pied2.render(f5);
    pied3.render(f5);
    pied4.render(f5);
    pied1.render(f5);
    siege.render(f5);
    barre.render(f5);
    barre1.render(f5);
    barre2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }
  
  public void renderModel(float f)
  {
	    pied1.render(f);
	    pied2.render(f);
	    pied3.render(f);
	    pied4.render(f);
	    siege.render(f);
	    barre.render(f);
	    barre1.render(f);
	    barre2.render(f);
  }

}
